#!/usr/bin/env bash

if
  [[ -s "/Users/michaeljang/.rvm/gems/ruby-2.2.3@global/environment" ]]
then
  source "/Users/michaeljang/.rvm/gems/ruby-2.2.3@global/environment"
  exec ruby "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/michaeljang/.rvm/gems/ruby-2.2.3@global/environment'" >&2
  exit 1
fi
