### CUSTOM PROMPT
export PROMPT_COMMAND='echo -n "]1;$PWD"'
export PS1="\
\[\e[33m\]/...\
\[\e[36m\]\W \
\[\e[32m\]>>> \
\[\e[0m\]"
###
# "\[\e[36m\]\A\"	shows time in cyan
# "\[\e[33m\]/...\"	shows "/..." in yellow
# "\[\e[36m\]\W \"	shows "~" in cyan
# "\[\e[32m\]\>>> \"	shows ">>>" in green
# "\[\e[0m\]"		resets to white



# Setting PATH
PATH=$PATH:/Users/michaeljang/ubin
#  for Python 2.7
PATH=$PATH:/Library/Frameworks/Python.framework/Versions/2.7/bin
export PATH


#include ruby
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi


### ALIASES
alias ls='ls -F'
# -F displays '/' after each directory, '*' after executables, etc
# -1 formats one entry per line
# -A displays all entries except . and .. .
alias ll="ls -l"
alias la="ls -A"
alias lla="ls -lA"
alias l1="ls -1"
alias df="df -h"
alias rm="rm -i"
alias print="echo"
alias eject="diskutil eject"
alias py3="python3.2"

# McGill SSH and SCP aliases
alias scp="scp -r"
alias sshu="ssh mjang1@ubuntu.cs.mcgill.ca"
alias sshf="ssh mjang1@freebsd.cs.mcgill.ca"
alias sshm="ssh mjang1@mimi.cs.mcgill.ca" #for password changes
mm="mjang1@ubuntu.cs.mcgill.ca"
school="mjang1@ubuntu.cs.mcgill.ca:/home/2011/mjang1"

#alias sshmimi="ssh mjang1@mimi.cs.mcgill.ca"
#mm="mjang1@mimi.cs.mcgill.ca"
#school=mjang1@mimi.cs.mcgill.ca:/home/2011/mjang1"

# Virtual Box aliases
alias vbm="VBoxManage"







### COLOURS
#\[\e[0m\]  0=reset to default \n\
#\[\e[30m\] 30=black \n\
#\[\e[31m\] 31=red \n\
#\[\e[32m\] 32=green \n\
#\[\e[33m\] 33=yellow \n\
#\[\e[34m\] 34=blue \n\
#\[\e[35m\] 35=magenta \n\
#\[\e[36m\] 36=cyan
