#!/usr/bin/env bash

if
  [[ -s "/Users/michaeljang/.rvm/gems/ruby-2.2.1/environment" ]]
then
  source "/Users/michaeljang/.rvm/gems/ruby-2.2.1/environment"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/michaeljang/.rvm/gems/ruby-2.2.1/environment'" >&2
  exit 1
fi
